### ISSUE TITLE
War Log

### ISSUE THREAD

**Issue by richard4339** [toniperic/php-clash-of-clans#6]
Are you going to update to support the war log they added to the API?

**Comment by toniperic** [comment]
Hello @richard4339 and thank you for your question.

I've been very busy lately due to summer holidays having to sub colleagues and also due to my personal vacations.
I probably am going to make some changes to the package when I get some time to do it, but you're also more than welcome to contribute.

Hope that answers your question so I'm going to close this one out.
Cheers!

**Comment by chgasparoto** [comment]
@richard4339 I implemented a draft on my fork. If you want, take a look on develop branch please.
